config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'
  
  
  get '/wellcome', to: 'static_pages#index', as: 'static_pages_wellcome'
  get '/about', to: 'static_pages#about', as: 'static_pages_about'
  get '/main', to:'static_pages#main', as:'main_page'

  # User routes
  devise_for :users
  devise_scope :user do
    get 'users/profile/:id', to: 'users#show', as: 'users_profile'
    get 'users/sign_up/file', to:'registrations#file', as:'registrations_file'
  end
  resources :users

  resources :sub_reddits do

     post '/join', to:'sub_reddits#join', as:'join'
     post '/leave', to:'sub_reddits#leave', as:'leave'    
     resources :posts do

      resources :comments
       
     end
  end
  
  resources :users
end

app/models/sub_reddit.rb
class SubReddit < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_one_attached :background_picture

  validates :title, :description, presence: true
  validates :title, length: { minimum: 5, maximum: 50 }
  validates :description, length: { minimum: 10, maximum: 200 }

  has_many :user_sub_reddits
  has_many :members, through: :user_sub_reddits, :source  => :user


  
  #  returns the join status of the user
  #  accepted pending or blocked
  def current_user_joined(usr)
    found = nil
    begin
     found = self.user_sub_reddits.where(user_id: usr.id).first.status  
    rescue Exception => e
    end
  	found
  end


  # returns top five communities based on
  # number of posts
  def self.todays_top_ten
     SubReddit.order('posts_count').limit(10)
  end


  def comments_count

    posts = self.posts
    count = 0
    posts.each do |post|
      count += post.comments.size
    end
    count
  end
end

app/controllers/sub_reddits_controller.rb
# frozen_string_literal: true

class SubRedditsController < ApplicationController
  before_action :authenticate_user!
  def index
    @subreddits = SubReddit.all
  end

  def new
    @sub_reddit = SubReddit.new
  end

  def show
    @sub_reddit = SubReddit.find(params[:id])
    @post = Post.new
    @status = @sub_reddit.current_user_joined(current_user)
  end

  def edit
    @sub_reddit = SubReddit.find(params[:id])
    
  end

  def create
    @sub_reddit = SubReddit.new(sub_reddit_params)
    @sub_reddit.user = current_user
    if @sub_reddit.save
      flash[:primary] = @sub_reddit.title+' created successfuly'
      redirect_to sub_reddits_path
    else 
      render :new
    end
  end

  def join
    usr =  UserSubReddit.new(
      user: current_user,
      sub_reddit_id: params[:sub_reddit_id],
      status: UserSubReddit.statuses[:accepted])
    
    if usr.save
      flash[:success] = 'Joined successfully'
      redirect_to sub_reddit_path(params[:sub_reddit_id])
    else 
      flash[:danger] = 'There was a problem'
      redirect_to sub_reddit_path(params[:sub_reddit_id])
    end
  end

  def leave 
    usr = UserSubReddit.where(user: current_user,sub_reddit_id: params[:sub_reddit_id]).first

    if UserSubReddit.destroy(usr.id)
      flash[:success] = 'You left this subreddit'
      redirect_to sub_reddit_path(params[:sub_reddit_id])
    else
      flash[:danger] = 'There was a problem'
      redirect_to sub_reddit_path(params[:sub_reddit_id])
    end
  end

  private
  def sub_reddit_params
    params.require(:sub_reddit).permit(:title, :description, :background_picture)
  end
end

app/helpers/sub_reddits_helper.rb
module SubRedditsHelper
end

app/views/sub_reddits/edit.html.erb
<div class="columns">
  <div class="column is-3"></div>
  <div class="column is-6">
    <%= form_for @sub_reddit, method: 'put' do |f|  %>
      <div class="field">
        <div class="control">
          <%= f.label :title, class: 'label' %>
          <%= f.text_field :title, class:'input',placeholder: '' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :description, class: 'label' %>
          <%= f.text_area :description,
                class: 'textarea', cols: 20, rows: 5, 
                placeholder: 'Type a breif descripton about this subreddit' %>
        </div>
      </div>

        <label class="label">Profile picture </label>
                  <div class="file" >
        <div class="file is-info has-name">
          <%= f.label :background_picture,class:"file-label"  do %>
            <div class="control">
              <%= f.file_field :background_picture,class:"file-input" %>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
            </div>
            <span class="file-name">
            </span>
          <% end %>
        </div>
      </div>

      <div class="control">
      <br/>
            <%= f.submit 'Create SubReddit',class:'button is-primary'  %>
      </div>
    <% end %>
  <div class="column is-3"></div>
</div>

app/views/sub_reddits/index.html.erb
<div class="row">
	<p class="text-info">Work in progress</p>
	
	<% @subreddits.each do |sub|  %>
	<div class="card">
		<div class="card-title">
			<%= sub.title %>	
		</div>
	</div>

	<% end %>
</div>

app/views/sub_reddits/new.html.erb
<div class="columns">
  <div class="column is-3"></div>
  <div class="column is-6">
    <%= form_for @sub_reddit, method: 'post' do |f|  %>
      <div class="field">
        <div class="control">
          <%= f.label :title, class: 'label' %>
          <%= f.text_field :title, class:'input',placeholder: '' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :description, class: 'label' %>
          <%= f.text_area :description,
                class: 'textarea', cols: 20, rows: 5, 
                placeholder: 'Type a breif descripton about this subreddit' %>
        </div>
      </div>

        <label class="label">Profile picture </label>
                  <div class="file" >
        <div class="file is-info has-name">
          <%= f.label :background_picture,class:"file-label"  do %>
            <div class="control">
              <%= f.file_field :background_picture,class:"file-input" %>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Choose a file…
                </span>
              </span>
            </div>
            <span class="file-name">
            </span>
          <% end %>
        </div>
      </div>

      <div class="control">
      <br/>
            <%= f.submit 'Create SubReddit',class:'button is-primary'  %>
      </div>
    <% end %>
  <div class="column is-3"></div>
</div>

app/views/sub_reddits/show.html.erb
<!-- background -->
<div>
  <% if @sub_reddit.background_picture.attached? %>
  <%=  image_tag @sub_reddit.background_picture, 
  class:'backgroung-img', alt:'subreddit picture' %>
<% end %>
</div>
<div class="row m-3">
  <h2 class="card-title shift-down-spacer">
  	<%= @sub_reddit.title %>
  	<% unless @status == nil  %>
			<% if @status == 'accepted' %>
				<%= link_to("Leave Community", sub_reddit_leave_path(@sub_reddit),method:'POST', class:'btn btn-sm btn-outline-danger') %>
			<% end %>
			<% if @status == 'pending' %>
			<%= link_to("Cancel Request", sub_reddit_leave_path(@sub_reddit),method:'POST', class:'btn btn-sm btn-outline-warning')  %>
			<% end %>
		<% else %>
	<%= link_to("Join", sub_reddit_join_path(@sub_reddit),method:'POST', class:'btn btn-sm btn-outline-info') %>	
  	<% end %>
  </h2> 
</div>
<div class="row">
  <div class="col-md-9">

    <!-- post form -->
    <div class="card m-1" style="background-color: rgba(0, 0, 0, 0.03);">
      <div class="card-body">
             <%= form_with(url: sub_reddit_posts_url(sub_reddit_id: @sub_reddit.id), method:'POST', remote: false) do |f| %>
  <div class="form-group">
        <%= f.label :title %><br />
        <div class="control">
          <%= f.text_field :title, autofocus: true, autocomplete: "email",class:"form-control" %>
        </div>
  </div>
  <div class="form-group">
      <%= f.label :content %><br />
      <%= f.text_area :content,rows:3,class:'form-control' %>
  </div>
  <%= f.submit "Post",class:"btn btn-outline-primary"  %>
<% end %>      
      </div>
    </div>
  <br/>
  <!-- posts list -->
  <div>
      <% @sub_reddit.posts.each do |post| %>
        <%= render partial:'shared/posts/post_card', locals: {post:post,top:false} %>
      <% end %>
  </div>


  </div>
  <!-- post details -->
  
  <div class="col-md-3 pl-0 pr-0 mt-1">
    <div class="card">
  <div class="card-header">
    About This Community
  </div>
  <div class="card-body">
    <!-- <h5 class="card-title">Special title treatment</h5> -->
    <p class="card-text"> <%= @sub_reddit.description %> </p>
    <div class="row mt-2 mb-2">
      <div class="col-md-4">
        <div class="text-muted" style="font-size: 0.70rem; font-weight: bold; text-align: center;">
          <i class="fas fa-users"></i>
          <div>
          MEMBERS  
          </div>
          
        </div>
        <div style="text-align: center;">
          <%= @sub_reddit.members.size %>
        </div>
      </div>
      <div class="col-md-4" >
        
          <div class="text-muted" style="font-size: 0.70rem; font-weight: bold; text-align: center;">
             <i class="fas fa-list-alt"></i>
             <div>POSTS</div>
               
          </div>
          <div style="text-align: center;">
            <%= @sub_reddit.posts.size %>
          </div>
                  
        
      </div>
      <div class="col-md-4 pl-0">
        <div class="text-muted" style="font-size: 0.70rem; font-weight: bold; text-align: center;">
          <i class="far fa-comment-alt"></i>
          COMMENTS
        </div>
        <div style="text-align: center;">
          <%= @sub_reddit.comments_count %>
        </div>
      </div>
    </div>
    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
  </div>
</div>
  </div>
 
</div>