config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'
  
  
  get '/wellcome', to: 'static_pages#index', as: 'static_pages_wellcome'
  get '/about', to: 'static_pages#about', as: 'static_pages_about'
  get '/main', to:'static_pages#main', as:'main_page'

  # User routes
  devise_for :users
  devise_scope :user do
    get 'users/profile/:id', to: 'users#show', as: 'users_profile'
    get 'users/sign_up/file', to:'registrations#file', as:'registrations_file'
  end
  resources :users

  resources :sub_reddits do

     post '/join', to:'sub_reddits#join', as:'join'
     post '/leave', to:'sub_reddits#leave', as:'leave'    
     resources :posts do

      resources :comments
       
     end
  end
  
  resources :users
end

app/views/shared/_comment_form.html.erb
<div class="card">
	<div class="card-header">
<%= form_for @comment,url: sub_reddit_post_comments_path(post_id: params[:id]), method: 'post' do |f| %>
  <div class="form-group">
    <div class="control">
      <%= f.label :content,'Write a comment'%>
      <%= f.text_area :content,
                class: 'form-control', 
                placeholder: 'Write a comment' %>
    </div>
  </div>
 <%= f.submit "Comment",class:"btn btn-outline-primary" %>
<% end %>		

	</div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Reddit Clone</strong> by <a href="https://github.com/azdrenymeri">Azdren Ymeri</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.
    </p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light" style="background-color: #e3f2fd;" >
  
    <a class="navbar-brand" href=<%= static_pages_wellcome_path %> >
      <%= image_tag("reddit.png", :alt => "logo", :width => '30', :height => '30', :class => 'd-inline-block align-top') %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <% if user_signed_in? %>
  <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle subredit-dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fas fa-home"></i> Home
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            
            <%= link_to root_path,class:'dropdown-item dropdown-header' do  %>
            <i class="fas fa-home"></i> Home
            <% end %>

          <% current_user.joined_communities.each do |sub_reddit| %>

            <%= link_to sub_reddit_path(sub_reddit), class:'dropdown-item' do %>
                <%= sub_reddit.title %>          
            <% end %>
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Comming Soon </a>

        </div>
      </li>
  </ul>

    
    <form class="form-inline mr-auto w-50">
      <input class="form-control mr-sm-2 w-100 p-3" type="search" placeholder="Search" aria-label="Search">
    </form>

    <ul class="navbar-nav">
      <% if current_user.picture.attached? %>
      <li class="nav-item dropdown">
         <a href=<%=edit_user_registration_url %> class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
           <%= image_tag current_user.picture ,class:"nav-user-icon"%>
           <%= current_user.full_name %>
         </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to edit_user_registration_path, class:"dropdown-item text-muted" do  %>
           <i class="fas fa-user-circle"></i> Profile 
          <% end %>
          <%= link_to new_sub_reddit_path,class:"dropdown-item text-muted" do %>
          <i class="fab fa-reddit-alien"></i> Create a SubReddit
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to destroy_user_session_path,method:"DELETE",class:"dropdown-item text-muted" do %>
          <i class="fas fa-sign-out-alt"></i> Sign Out
          <% end %>
        </div>
      </li>

       <% end %>
    </ul>

  <% else %>
     <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to static_pages_wellcome_path, class:'nav-link' do  %>
        <span>
       <i class="fas fa-home"></i> 
        Home
      </span>
      <% end %>
      </li>
      <li class="nav-item">

        <%= link_to static_pages_about_path, class:'nav-link' do %>
      <span>
        <i class="fas fa-question-circle"></i>  &nbsp;
        About
       </span>
      <% end %>
      </li>
    </ul>

    <ul class="navbar-nav"> 
      <li class="navbar-item">
         <%= link_to new_user_session_path, class:'btn btn-outline-info' do %>
              Sign in
            <i class="fas fa-sign-in-alt"></i>
        <% end %>
      </li>
      &nbsp;&nbsp;
      <li class="navbar-item">
        <%= link_to new_user_registration_path, class:'btn btn-secondary' do %>
        Sign up
          <i class="fas fa-user-plus"></i>
          
        <% end %>
      </li>
    </ul>
  <% end %>

 
  </div>
</nav>

app/views/shared/_sub_reddit_card.html.erb
<div class="card m-1">
        <div class="row no-gutters">
            <div class="col-3">
                <% if sub_reddit.background_picture.attached? %>
                    <%= link_to sub_reddit_path(sub_reddit),class:'text-decoration-none' do %>
                        <%= image_tag sub_reddit.background_picture, class:'card-img-top ',width:'140',height:'140',alt:'subreddit picture' %>
                    <% end %>
                <% end %>
            </div>
            <div class="col">
                <div class="card-block px-2">
                    <%= link_to sub_reddit_path(sub_reddit),class:'text-decoration-none' do %>
                        <h5 class="text-decoration-none m-2"> <%= sub_reddit.title %> </h5>
                    <% end %>
                    <p class="card-text m-2"><%= sub_reddit.description %></p>
                    <a href="#" class="btn btn-sm btn-outline-primary">Join(comming soon)</a>
                </div>
            </div>
        </div>
</div>

app/views/shared/_top_communities_card.html.erb
<div class="card">
  <div class="card-header community-background-img" style="background:url(<%= url_for(top_communities.first.background_picture)  %>); ">
    Top Communities
  </div>

  <ul class="list-group list-group-flush">
  	<% top_communities.each do |sub_reddit| %>
    <li class="list-group-item">
    <%= link_to sub_reddit_path(sub_reddit.id),class:'communtiy-link' do  %>
    <%= image_tag(sub_reddit.background_picture,
       class:'community-icon') %> 
    <% end %>

       <%= link_to sub_reddit.title, sub_reddit_path(sub_reddit.id), class:'top-community-item' %> 
    
    </li>
    <% end %>
  </ul>
   <div class="card-body">
    <%= link_to("View All", sub_reddits_path , class:'btn btn-primary',style:'display:block;') %>
  </div>
</div>