config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'
  
  
  get '/wellcome', to: 'static_pages#index', as: 'static_pages_wellcome'
  get '/about', to: 'static_pages#about', as: 'static_pages_about'
  get '/main', to:'static_pages#main', as:'main_page'

  # User routes
  devise_for :users
  devise_scope :user do
    get 'users/profile/:id', to: 'users#show', as: 'users_profile'
    get 'users/sign_up/file', to:'registrations#file', as:'registrations_file'
  end
  resources :users

  resources :sub_reddits do

     post '/join', to:'sub_reddits#join', as:'join'
     post '/leave', to:'sub_reddits#leave', as:'leave'    
     resources :posts do

      resources :comments
       
     end
  end
  
  resources :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :sub_reddit, counter_cache: true
  belongs_to :user
  has_many :comments,counter_cache: true

  validates :sub_reddit,:user, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 30 }
  validates :content, presence: true, length: { minimum: 10, maximum: 2000 }


end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @newPost = Post.new(title: params[:title],
                        content: params[:content],
                        comments_count:0)
    @newPost.user_id = current_user.id
    @newPost.sub_reddit_id = params[:sub_reddit_id]
    
    if @newPost.save
      redirect_to sub_reddit_path(@newPost.sub_reddit_id)
    else
      flash[:danger] = @newPost.errors.full_messages.join(', ')
      redirect_to sub_reddit_path(@newPost.sub_reddit_id)
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/hello.js.erb
alert('hello.js.erb finished running');

console.log('Hello clicked');

app/views/posts/index.html.erb
<div class="columns">
<div class="column is-1"></div>
<div class="column is-9">
    <% @posts.each do |post| %>
      <%= post.title %>
    <% end %>
</div>
<div class="column is-2"></div>
</div>

app/views/posts/new.html.erb
<div class="columns">
    <div class="column is-2"></div>
    <div class="column is-8">
    <h1 class="title is-2">New Post</h1>
        <%= form_for @post ,url: sub_reddit_posts_path, method: 'post' do |f| %>
        <div class="field">
        <div class="control">
          <%= f.label :title, class:'label' %>
          <%= f.text_field :title, class:'input'%>        
        </div>
        </div>
             <div class="field">
        <div class="control">
          <%= f.label :content, class: 'label' %>
          <%= f.text_area :content,
                class: 'textarea', cols: 20, rows: 5, 
                placeholder: 'Content here' %>
        </div>
      </div>
      <%= f.submit class:"button is-primary"%>
        <% end %>
    </div>
    <div class="column is-2"></div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-9">
      <article class="message is-primary card">
        <div class="card-body">
        <div class="message-header">
          <h1><%= @post.title %></h1>
        </div>
        <div class="message-body">
          <%= @post.content %>
        </div>  
        </div>
      </article>
      <div class="row mt-3">
        <div class="col-md-8">
          <%= render 'shared/comment_form' %>    
        </div>
      </div>
      
      <hr />
      <% @post.comments.each do |comment| %>
        <article class="message message-margin">
          <div class="message-body bottom-border">
            <%= comment.content %>
          </div>
        </article>
      <% end %>
    </div>
  </div>
</div>