config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'
  
  
  get '/wellcome', to: 'static_pages#index', as: 'static_pages_wellcome'
  get '/about', to: 'static_pages#about', as: 'static_pages_about'
  get '/main', to:'static_pages#main', as:'main_page'

  # User routes
  devise_for :users
  devise_scope :user do
    get 'users/profile/:id', to: 'users#show', as: 'users_profile'
    get 'users/sign_up/file', to:'registrations#file', as:'registrations_file'
  end
  resources :users

  resources :sub_reddits do

     post '/join', to:'sub_reddits#join', as:'join'
     post '/leave', to:'sub_reddits#leave', as:'leave'    
     resources :posts do

      resources :comments
       
     end
  end
  
  resources :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :sub_reddit, counter_cache: true
  belongs_to :user
  has_many :comments,counter_cache: true

  validates :sub_reddit,:user, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 30 }
  validates :content, presence: true, length: { minimum: 10, maximum: 2000 }


end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @newPost = Post.new(title: params[:title],
                        content: params[:content],
                        comments_count:0)
    @newPost.user_id = current_user.id
    @newPost.sub_reddit_id = params[:sub_reddit_id]
    
    if @newPost.save
      redirect_to sub_reddit_path(@newPost.sub_reddit_id)
    else
      flash[:danger] = @newPost.errors.full_messages.join(', ')
      redirect_to sub_reddit_path(@newPost.sub_reddit_id)
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/shared/posts/_post_card.html.erb
<div class="card m-1">
  <div class="card-body">
      <% if top %>
    
    <%= image_tag(post.sub_reddit.background_picture,
       class:'sub-reddit-icon') %> 
    <span class="card-subtitle mb-2 text-muted"> 
      <%= link_to('r/'+post.sub_reddit.title, 
      sub_reddit_path(post.sub_reddit.id),class:'text-muted top-text') %> 
    </span>
     <% else %>
     <%= link_to(users_profile_path(post.user.id),style:'text-decoration: none') do  %>
    <%= image_tag(post.user.picture,
       class:'sub-reddit-icon') %>
       <% end %> 
  <% end %>  

	<span class=" text-muted top-text">
		Posted by <%= link_to(post.user.full_name,users_profile_path(post.user.id), class:'text-muted top-text')  %>
	</span>
	<span class="text-muted top-text">
		<%= time_ago_in_words(post.created_at)+' ago' %>
	</span>
    <h5 class="card-title mt-2">
    <%= link_to(post.title,sub_reddit_post_path(
      sub_reddit_id: post.sub_reddit.id,
      id: post.id) , class:'link-mod') %> 
    </h5>  
    <p class="card-text"> <%= post.content %> </p>
  </div>
  <div class="card-footer p-1 footer-mod" style="padding-left: 1.25rem !important;">

    <div class="text-muted text-bottom">
      
      <%= 
      link_to sub_reddit_post_path(
      sub_reddit_id: post.sub_reddit.id,
      id: post.id),class:'text-muted' do  %> 
      <i class="far fa-comment-alt"></i> 
      <%= count_format(post.comments.count)  %> Comments</div>
      <% end %>
  </div>
</div>

app/views/shared/posts/_post_form.html.erb
<h1>Post Form </h1>
<%= form_with(url: sub_reddit_posts_url,validation:true) do |f| %>
	<div class="form-group">
        <%= f.label :title %><br />
        <div class="control">
          <%= f.text_field :title, autofocus: true, autocomplete: "email",class:"form-control" %>
        </div>
     </div>
<% end %>